# Generated by Django 2.2 on 2020-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
